language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.3

    - android-25

notifications:
  email: false

sudo: false

before_install:
  # Danger needs rvm 2.0.0 and the only way to get it is this according to
  # https://stackoverflow.com/questions/30242585/travis-ci-not-switching-to-the-specified-ruby-version-on-an-android-project-buil
  - rvm install 2.0.0

before_script:  # Danger
  - bundle install
  - bundle exec danger

script:
  - ./gradlew assembleRelease  # Build the artifact

after_success:
  - ./gradlew artifactoryPublish  # Publish if successful

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle