language: android
# For danger
rvm:
  - 2.0.0

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.3

    - android-25

notifications:
  email: false

sudo: false

before_script:
  # Danger
  - bundle install
  - bundle exec danger